/* eslint-disable global-require */

module.exports = {
  createHostedCheckout: require('./hostedCheckouts/create.json'),
  createHostedMandateManagement: require('./hostedMandateManagements/create.json'),
  createPayment: require('./payments/create.json'),
  completePayment: require('./payments/complete.json'),
  tokenizePayment: require('./payments/tokenize.json'),
  approvePayment: require('./payments/approve.json'),
  capturePayment: require('./payments/capture.json'),
  refundPayment: require('./payments/refund.json'),
  createPaymentDispute: require('./payments/dispute.json'),
  approveRefund: require('./refunds/approve.json'),
  createPayout: require('./payouts/create.json'),
  getDeviceFingerprintForGroups: require('./productGroups/deviceFingerprint.json'),
  getCustomerDetails: require('./products/customerDetails.json'),
  getDeviceFingerprint: require('./products/deviceFingerprint.json'),
  createPaymentProductSession: require('./products/sessions.json'),
  riskAssessmentBankAccount: require('./riskAssessments/bankAccounts.json'),
  riskAssessmentCards: require('./riskAssessments/cards.json'),
  convertBankAccount: require('./services/bankAccount.json'),
  iinDetails: require('./services/getIINdetails.json'),
  createToken: require('./tokens/create.json'),
  updateToken: require('./tokens/update.json'),
  approveSepaDirectDebitToken: require('./tokens/approveSepaDirectDebit.json'),
  createMandate: require('./mandates/create.json'),
  createMandateWithReference: require('./mandates/createWithMandateReference.json'),
  createSession: require('./sessions/create.json'),
};
